### PR TITLE
Added functionality to prevent password from showing up as plaintext.

### PR DESCRIPTION
**Pull request by LX5321**
# More secure form of login without revealing user entered password.

Reference issue: #9 

## Old Feature

``` 
alexander@lx:~/instagram-bomber$ python3 bomber.py 
Put your Instagram accounts list here (if there is no file just press ENTER): 
Put your IG Username then press ENTER: (sample_account)
Put your IG Password then press ENTER: (sample_account_password_revealed)
Request return 405 error!
{'message': '', 'status': 'fail'}
Request return 404 error!
Login success!

Enter the victim's IG Username: ^C

Put your Instagram accounts list here (if there is no file just press ENTER): ^C
See you soon :)

```

## New Feature

```
alexander@lx:~/instagram-bomber$ python3 bomber.py 
Put your Instagram accounts list here (if there is no file just press ENTER): 
Put your IG Username then press ENTER: (sample_instagram_account)
Put your IG Password then press ENTER: 
Got Password. Attempting to login.
Request return 405 error!
{'message': '', 'status': 'fail'}
Request return 404 error!
Login success!

Enter the victim's IG Username: ^C

Put your Instagram accounts list here (if there is no file just press ENTER): ^C
See you soon :)

```

### Summary: Password is not revealed when typed in by user.

### CODE REVIEW

**Comment by LX5321** [comment]
# Parsed JSON

Raw JSON looks unreadable and also has unnecessary information for the user, therefore by parsing the JSON and extracting only what is needed we can maintain the debugging functionality alongside a user ready product.

## Old Feature

```
alexander@lx:~/clone/instagram-bomber$ python3 bomber.py 
Put your Instagram accounts list here (if there is no file just press ENTER): 
Put your IG Username then press ENTER: de
Put your IG Password then press ENTER: 
Got Password. Attempting to login.
Request return 400 error!
{'message': 'The password you entered is incorrect. Please try again.', 'invalid_credentials': True, 'error_title': 'Incorrect password for de', 'buttons': [{'title': 'Try Again', 'action': 'dismiss'}], 'status': 'fail', 'error_type': 'bad_password'}
Enter the victim's IG Username: ^C

Put your Instagram accounts list here (if there is no file just press ENTER): ^[[A^C
See you soon :)

```

## New Feature

```
alexander@lx:~/clone/instagram-bomber$ python3 bomber.py 
Put your Instagram accounts list here (if there is no file just press ENTER): 
Put your IG Username then press ENTER: sample_username
Put your IG Password then press ENTER: 
Got Password. Attempting to login.
Request return 400 error!

🛑 Title:  Incorrect password for sample_username
🛑 Error Message:  The password you entered is incorrect. Please try again.
🛑 Status:  fail
🛑 Error Type:  bad_password
Enter the victim's IG Username:^C

Put your Instagram accounts list here (if there is no file just press ENTER):^C
See you soon :)
```

### JSON parsed for better readability and more intuitive user interface.

**Comment by LX5321** [comment]
# Infinite Loop Prevented Program Termination

Reference Issue: #12 

## Old Feature

```
alexander@lx:~/clone/instagram-bomber$ python3 bomber.py 
Put your Instagram accounts list here (if there is no file just press ENTER): 
Put your IG Username then press ENTER: sample_username
Put your IG Password then press ENTER: 
Got Password. Attempting to login.
Request return 400 error!

🛑 Title:  Incorrect password for sample_username
🛑 Error Message:  The password you entered is incorrect. Please try again.
🛑 Status:  fail
🛑 Error Type:  bad_password
Enter the victim's IG Username: 
Unknown victim's username
Put the message you want the software send and press ENTER: 
How many messages do you want to send? 
Wrong number
How many messages do you want to send? 
Wrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? ^CWrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? Wrong number
How many messages do you want to send? 
Program Terminated: SIGTERM RECEIVED <@30582>
```

## New Feature

```
alexander@lx:~/clone/instagram-bomber$ python3 bomber.py 
Put your Instagram accounts list here (if there is no file just press ENTER): 
Put your IG Username then press ENTER: sample
Put your IG Password then press ENTER: 
Got Password. Attempting to login.
Request return 400 error!

🛑 Title:  Incorrect password for sample
🛑 Error Message:  The password you entered is incorrect. Please try again.
🛑 Status:  fail
🛑 Error Type:  bad_password
Enter the victim's IG Username: ^[[A
Unknown victim's username
Program will now terminate. Kindly identify victim account.

A critical error happened. Please make sure that you executed all commands properly and relaunch the program.
```
### Summary: The infinite loop and exit blocking code was handled successfully. :clinking_glasses:

**Comment by LX5321** [comment]
# Program Logic Error

Reference Issue: #13 

## Old Version

```
alexander@lx:~/clone/instagram-bomber$ python3 bomber.py 
Put your Instagram accounts list here (if there is no file just press ENTER): 
Put your IG Username then press ENTER: de
Put your IG Password then press ENTER: 
Got Password. Attempting to login.
Request return 400 error!

🛑 Title:  Incorrect password for de
🛑 Error Message:  The password you entered is incorrect. Please try again.
🛑 Status:  fail
🛑 Error Type:  bad_password
Whoops. Couldnt login.
Enter the victim's IG Username: ^[[A^C

Put your Instagram accounts list here (if there is no file just press ENTER): ^C
See you soon :)

```

## New Version

```
alexander@lx:~/clone/instagram-bomber$ python3 bomber.py 
Put your Instagram accounts list here (if there is no file just press ENTER): 
Put your IG Username then press ENTER: k
Put your IG Password then press ENTER: 
Got Password. Attempting to login.
Request return 400 error!

🛑 Title:  Incorrect password for k
🛑 Error Message:  The password you entered is incorrect. Please try again.
🛑 Status:  fail
🛑 Error Type:  bad_password

Whoops. Couldn't login. Check the above flags to know more.

A critical error happened. Please make sure that you executed all commands properly and relaunch the program.

```

### Summary: Since the user wasn't logged in there would be definite failure. Preventing this is essential.

**Comment by Gumbraise** [comment]
Thanks a lot mate 🥇

**Pull request merged**
